function f_tilda = calculateAnalyticTractions(rn, links, gamma_dln, xnodes, a, MU, NU, ...
        f_tilda, x3x6, n_nodes, n_nodes_t, n_se, idxi, f_tilda_node, ...
        f_tilda_se, use_gpu, n_threads, para_scheme, para_tol)
    [x1x2, b, n_dln] = extract_dislocation_nodes(rn, links);
    [f_tilda, ~] = analytic_traction(x3x6, x1x2, b, n_nodes, n_nodes_t, ...
        n_se, n_dln, 3 * gamma_dln(:, 1), idxi, f_tilda_node, f_tilda_se, ...
        f_tilda, MU, NU, a, use_gpu, n_threads, para_scheme, para_tol);
end
