function [sign_u_dot, u_dot, sign_f_dot, f_dot, u_tilda_0, u, u_hat, u_tilda] = constantLoading(...
        sign_u_dot, u_dot, sign_f_dot, f_dot, u_tilda_0, u, f_bar, f_hat, f_tilda, u_bar, ...
        u_hat, u_tilda, r_hat, simTime, totalSimTime, curstep, calculateLoadingFunctionArgs)
    return
end
