function [rnnew, linksnew, connectivitynew, linksinconnectnew, fsegnew] = remeshPreCollision(rnnew, linksnew, ...
        connectivitynew, linksinconnectnew, fsegnew, lmin, lmax, areamin, areamax, MU, NU, a, Ec, ...
        mobility, rotMatrix, doremesh, dovirtmesh, vertices, u_hat, nc, xnodes, D, mx, mz, w, h, d, ...
        TriangleCentroids, TriangleNormals, CUDA_flag, Bcoeff)

    if doremesh% do virtual re-meshing first
        %remeshing virtual dislocation structures
        if dovirtmesh
            [rnnew, linksnew, connectivitynew, linksinconnectnew, fsegnew] = virtualmeshcoarsen(rnnew, linksnew, ...
                connectivitynew, linksinconnectnew, fsegnew, MU, NU, a, Ec);
        end

        %remeshing internal dislocation structures
        [rnnew, linksnew, connectivitynew, linksinconnectnew, fsegnew] = remesh_all(rnnew, linksnew, ...
            connectivitynew, linksinconnectnew, fsegnew, lmin, lmax, areamin, areamax, MU, NU, a, Ec, ...
            mobility, rotMatrix, doremesh, dovirtmesh, vertices, u_hat, nc, xnodes, D, mx, mz, w, h, d, ...
            TriangleCentroids, TriangleNormals, CUDA_flag, Bcoeff);
    end

end
